# Generated by Django 2.0.7 on 2018-08-22 08:08

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20161108_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='books/empty_cover.jpg', upload_to=store.models.cover_upload_path),
        ),
        migrations.AlterField(
            model_name='review',
            name='latitude',
            field=models.FloatField(default='37.419', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='longitude',
            field=models.FloatField(default='122.05', max_length=20),
        ),
    ]
