# Generated by Django 2.0.7 on 2018-08-25 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20180822_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='bookorder',
            name='orderId',
            field=models.IntegerField(default=1.3436424411240122),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.BookOrder'),
        ),
    ]
