# Generated by Django 2.0.7 on 2018-09-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20180825_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='orderId',
            field=models.IntegerField(default=18134063),
        ),
    ]
