#!/bin/bash
echo "enter Sendgrid email server password"
read password
export DJANGO_EMAIL_PASSWORD=$password
echo "the password has been set to $DJANGO_EMAIL_PASSWORD"

echo "killall uwsgi process"
sudo killall -s9 uwsgi
sleep 3
echo "restart uwsgi process"
uwsgi --ini /home/azureuser/django/uwsgi.ini >>/home/azureuser/tmp/uwsgi.log 2>&1 &
